import os
import json
import time
import logging
import sqlite3

from pathlib import Path
from flask import Flask, jsonify, request, render_template
from threading import RLock

from core.config import CONFIG, load_config, save_config
from core.db_manager import (
    DB_PATH,
    reset_test_mode_state,
    fetch_recent_trades,
    fetch_equity_from_db,
    fetch_open_positions_db,
    ensure_tables_exist,
)
from ai.ai_sizer import AISizer
from ai.ai_performance import get_ai_performance
from core.ws_bridge import get_price
from core.paper_account import get_account_state

app = Flask(__name__)

BASE_DIR = Path(__file__).resolve().parent
CORE_DIR = BASE_DIR.parent / "core"

CONFIG_PATH = CORE_DIR / "config.json"
DEFAULT_CONFIG_PATH = CORE_DIR / "config_default.json"

_state_lock = RLock()
APP_START_TS = time.time()


@app.route("/")
def index():
    return render_template("dashboard.html")


@app.route("/settings")
def settings_page():
    return render_template("settings.html")


@app.route("/trades")
def trades_page():
    return render_template("trades.html")


@app.route("/compat")
def compat_page():
    return render_template("compat_report.html")


@app.route("/api/summary")
def api_summary():
    eq = fetch_equity_from_db()
    perf = get_ai_performance()
    acc = get_account_state()

    balance = acc.get("balance", 0)
    total_equity = balance + eq.get("unrealized_pnl", 0)
    pnl_pct = 0
    if acc.get("start_balance", 0) > 0:
        pnl_pct = round(((total_equity - acc["start_balance"]) /
                         acc["start_balance"]) * 100, 3)

    return jsonify({
        "balance": balance,
        "equity": total_equity,
        "pnl_pct": pnl_pct,
        "open_positions": len(fetch_open_positions_db()),
        "ai_win_rate": perf.get("win_rate", 0),
        "ai_trades": perf.get("total_trades", 0),
        "ai_profit_usdc": perf.get("profit_usdc", 0)
    })


@app.route("/api/open_positions")
def api_open_positions():
    pos = fetch_open_positions_db()
    out = []
    for p in pos:
        sym = p["symbol"]
        price = get_price(sym)
        if price is None:
            price = p["entry_price"]

        out.append({
            "symbol": sym,
            "qty": p["qty"],
            "entry_price": p["entry_price"],
            "current_price": price,
            "pnl": round((price - p["entry_price"]) * p["qty"], 6)
        })
    return jsonify(out)


@app.route("/api/live_positions")
def api_live_positions():
    pos = fetch_open_positions_db()
    return jsonify(pos)


@app.route("/api/ai_summary")
def api_ai_summary():
    return jsonify(get_ai_performance())


@app.route("/api/ai_performance")
def api_ai_performance():
    return jsonify(get_ai_performance())


@app.route("/api/ai_sizer")
def api_ai_sizer():
    s = AISizer()
    return jsonify(s.get_summary())


@app.route("/api/ai_metrics")
def api_ai_metrics():
    limit = int(request.args.get("limit", 100))
    trades = fetch_recent_trades(limit)
    return jsonify(trades)


@app.route("/api/runtime")
def api_runtime():
    uptime = round(time.time() - APP_START_TS)
    return jsonify({"uptime_sec": uptime})


@app.route("/api/risk_summary")
def api_risk_summary():
    eq = fetch_equity_from_db()
    acc = get_account_state()
    balance = acc.get("balance", 0)
    current_dd = eq.get("drawdown_pct", 0)
    max_dd = CONFIG.get("RISK_MAX_DRAWDOWN_PCT", 25)

    return jsonify({
        "balance": balance,
        "drawdown_pct": current_dd,
        "drawdown_limit_pct": max_dd,
        "state": "OK" if current_dd < max_dd else "STOP"
    })


@app.route("/api/check_compat_matrix")
def api_check_matrix():
    try:
        path = BASE_DIR / "COMPAT_MATRIX_AUTO.md"
        report = [
            "# Compatibility Matrix (Auto)",
            "## API endpoints OK",
            f"- equity source: DB_ONLY",
            f"- trades source: DB_ONLY",
            f"- paper_account: OK",
            f"- ai_metrics: DB_OK",
            f"- config: {CONFIG_PATH.name}",
            "",
            "Autogenerated ✔"
        ]
        path.write_text("\n".join(report), encoding="utf-8")
        return jsonify({"status": "ok"})
    except Exception as e:
        return jsonify({"status": "error", "msg": str(e)})


@app.route("/api/save_config", methods=["POST"])
def api_save_config():
    data = request.json
    with _state_lock:
        for k, v in data.items():
            CONFIG[k] = v
        save_config(CONFIG)
    return jsonify({"status": "ok"})


@app.route("/api/get_config")
def api_get_config():
    return jsonify(CONFIG)


@app.route("/api/test_reset", methods=["POST"])
def api_test_reset():
    reset_test_mode_state()
    return jsonify({"status": "reset"})


if __name__ == "__main__":
    ensure_tables_exist()
    app.run(host="0.0.0.0", port=5000, debug=False)
